### ISSUE TITLE
[FEATURE REQ] Output sorted according to domain-name.

### ISSUE THREAD

**Issue by sujanchegu** [pesos/browser-history#10]
**Is your feature request related to a problem? Please describe.**
It would be helpful if the data provided by the lib can be sorted according to the domain name. 
Adding the above feature also allows the option of user providing an optional domain-name so that data related to the particular  domain can be given back to the user.

**Describe the solution you'd like**
A method in utils.py which sorts the list into a dict with key as the domain-name(string) and the value to be a list(datetime.datetime, string). A optional parameter which set by the user if he wants data related only to a particular domain.

**Comment by sujanchegu** [comment]
I want to work on this issue.

**Comment by Samyak2** [comment]
Sure :+1:
