### ISSUE TITLE
[BROWSER] Vivaldi browser support

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#102]
**Describe the browser and provide any links if available**

Browser name: [Vivaldi](https://vivaldi.com/)

It is based on chromium, should be easy to add support for this. Refer #48, #41, #24 

**List the platforms supported by the browser to be added**

 - [ ] Windows
 - [ ] Linux
 - [ ] Mac OS

**Comment by OBITORASU** [comment]
Can you please check the PR I made for this issue? I had to close the previous PR due to poor testing on my end, but the new PR seems to pass all the checks and Vivaldi support worked on my local machine (Linux) after the modifications.
