### ISSUE TITLE
[REFACTOR] add abstract classes for Chromium based browsers

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#104]
**The issue**

Currently, the `Chrome` class implements all functionality of Chromium based browsers. These browsers selectively use attributes of the `Chrome` class. This not only violates OOP principles but also leads to some amount of code repetition. The `browsers.py` file is quite large with methods such as `bookmarks_parser` taking nearly 100 lines of code, this can hinder the experience of first-time contributors to this repository.

**Solution**

Create ~~two classes~~ one class `ChromiumBasedBrowser` ~~and `FirefoxBasedBrowser`~~ that implements all of the attributes/methods of these browsers except for `name` and the paths (`linux_path`, `windows_path`, `mac_path`).
Then change the existing browsers to inherit from ~these two classes~ this class (except for `Safari` and `Firefox`).

The newly created ~~classes~~ class should go under `utils/browser.py` and the existing `utils.py` should be moved into `utils/__init__.py`.

---

Other ideas to solve this are welcome :)

**Comment by ObaraEmmanuel** [comment]
I have been looking at this and think we should add a `ChromiumBasedBrowser` class to `generic.py`. This, I think resonantes more with the sense that `ChromiumBaseBrowser` is in fact a generic abstract type. I don't know about `FirefoxBasedBrowser` because there are very few of those and they are not very conventional browsers (something like Tor doesn't store any application level data). We could just add the class if you intend to support those other minor Firefox based browsers.

**Comment by Samyak2** [comment]
> I have been looking at this and think we should add a `ChromiumBasedBrowser` class to `generic.py`

I don't think this should go to `generic.py` because that is already over 600 lines. Making a browser utils module to store this sounds better to me.

> I don't know about `FirefoxBasedBrowser` because there are very few of those and they are not very conventional browsers (something like Tor doesn't store any application level data).

That's a good point. Firefox based browsers aren't popular. The reason I wanted to make a separate class was because the `Firefox` class was quite large with functions like `bookmarks_parser` that make it look very complicated (more so in #103 which added more functions to this).

But yes, I agree with you, `FirefoxBasedBrowser` isn't required right now. I will change the description accordingly. Thank you.

**Comment by ObaraEmmanuel** [comment]
>I don't think this should go to generic.py because that is already over 600 lines. Making a browser utils module to store this sounds better to me.

I added the `ChromiumBasedBrowser` real quick to `generic.py` and it added up to 606 lines. `generic.py` is curently only 528 lines. Putting this class in `utils` would not make sense structurally. `ChromiumBasedBrowser` class is and will be a core functionality and not really a utility.

To reduce the size of the file we could break up heavy functionality to mixins and move them to separate files. Something like `Outputs.to_json` is a very huge function. I also agree that very huge files are not good for first-timers.

**Comment by lucasace** [comment]
> I don't know about `FirefoxBasedBrowser` because there are very few of those and they are not very conventional browsers (something like Tor doesn't store any application level data). We could just add the class if you intend to support those other minor Firefox based browsers.

But wont the bookmark parser in `Firefox` still be violating the OOP principle?
Where do we place that?

**Comment by Samyak2** [comment]
>`generic.py` is curently only 528 lines.

Right, I was looking a different branch :smile: 

> Putting this class in `utils` would not make sense structurally. `ChromiumBasedBrowser` class is and will be a core functionality and not really a utility.

Good point, it shouldn't be in utils but I want to break it up in some way.

> To reduce the size of the file we could break up heavy functionality to mixins and move them to separate files.

I'm not sure how we'll use mixins here, but yes this should be broken into separate files. `generic` isn't a great name, we should split into different modules.

**Comment by Samyak2** [comment]
> But wont the bookmark parser in `Firefox` still be violating the OOP principle?

I don't think that violates OOP as it's not used anywhere else. (Not sure about this)

**Comment by lucasace** [comment]
> Good point, it shouldn't be in utils but I want to break it up in some way.
Just a suggestion
`Helpers` part usually contain most of the core functionalities
Maybe make a `helpers.py` file 
A lot of future functions may go there too
