### ISSUE TITLE
[REFACTOR] fetch_map is overcomplicated

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#105]
**The issue**

[`fetch_map`](https://github.com/pesos/browser-history/blob/master/browser_history/cli.py#L90) used in the CLI is defined like this:
```python
    fetch_map = {
        "history": {"var": h_outputs, "fun": get_history},
        "bookmarks": {"var": b_outputs, "fun": get_bookmarks},
    }
```

The `var` key of the nested dict is not required since only one of `history` and `bookmarks` can be retrieved at a time. This can be replaced with a single variable to store the output.

**Solution**

Add a variable `outputs` to store the outputs and use the `fetch_map` only to map keyword to function:
```python
    fetch_map = {
        "history": get_history,
        "bookmarks": get_bookmarks,
    }
```

This will also require changes [here](https://github.com/pesos/browser-history/blob/master/browser_history/cli.py#L119).

**Comment by RajawatAmit** [comment]
Let me know if I can pick up this issue.

**Comment by Samyak2** [comment]
Sure, go ahead!
