### ISSUE TITLE
[BUG]Error fetching bookmarks from Opera on Windows

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#107]
**Describe the bug**
Trying to fetch bookmarks from Opera throws the error below:
```python
Traceback (most recent call last):
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\cli.py", line 123, in main
    fetch_map[args.type]["var"] = browser_class().fetch_bookmarks()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\generic.py", line 299, in fetch_bookmarks
    date_bookmarks = self.bookmarks_parser(copied_bookmark_path)
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\generic.py", line 602, in bookmarks_parser
    b_m["roots"][root]["children"], root, bookmarks_list
KeyError: 'children'
```

**To Reproduce**
Run the command
```browser-history -b opera -t bookmarks```
or even
```browser-history -t bookmarks```

**Expected behavior**
Should return the bookmarks in opera in CSV format

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - `browser-history` Version master
 - Python version: 3.8.0

**Additional context**
I tried the command after adding a few bookmarks to Opera. The command also fails for all formats and while fetching bookmarks from all browsers.
It's also important to remember that Opera has no profile support so this problem could be stemming from there.

**Comment by Samyak2** [comment]
Would it possible for you to add a sample of the history JSON file or the `b_m` dictionary here? If they aren't privacy infringing ofcourse.

The `b_m` dictionary is from here:
https://github.com/pesos/browser-history/blob/41b8539c5e42c470ddba11f79e1361387f449dfb/browser_history/generic.py#L587-L589

It would help us in debugging.

**Comment by ObaraEmmanuel** [comment]
Its a huge object to type out here so here's the json file

[dump.zip](https://github.com/pesos/browser-history/files/5661861/dump.zip)
