### ISSUE TITLE
[FEATURE REQ] Add python 3.9 to test workflow 

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#111]
**Is your feature request related to a problem? Please describe.**

The tests GitHub actions workflow currently uses python versions 3.6, 3.7 and 3.8. Since 3.9 was released a few months ago and `browser-history` works well on it, we should add 3.9 to the test workflow to ensure that it stays that way.

**Describe the solution you'd like**

Add `3.9` to the `python-version` list here:

https://github.com/pesos/browser-history/blob/42520ac23189907a1c52661b774e3122bc653e78/.github/workflows/python-package.yml#L16-L18

**Comment by RajawatAmit** [comment]
I'm happy to work on it.

**Comment by Samyak2** [comment]
You can go ahead and send a PR!
