### ISSUE TITLE
[BUG] CLI should show only the error instead of full traceback when given browser is not supported

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#124]
**Describe the bug**

When a particular browser is passed through the `-b`/`--browser` flag and if the browser is not supported on the current platform, a full python traceback is shown which is not ideal.

Example:
```powershell
$ browser-history -b safari
Traceback (most recent call last):
  File "D:\APPS\Miniconda\Scripts\browser-history-script.py", line 33, in <module>
    sys.exit(load_entry_point('browser-history', 'console_scripts', 'browser-history')())
  File "d:\dev\others\opensource\browser-history\browser_history\cli.py", line 144, in main
    cli(sys.argv[1:])
  File "d:\dev\others\opensource\browser-history\browser_history\cli.py", line 126, in cli
    outputs = browser_class().fetch_history()
  File "d:\dev\others\opensource\browser-history\browser_history\generic.py", line 125, in __init__
    assert self.windows_path is not None, error_string.format("windows")
AssertionError: Safari browser is not supported on windows
```

This is too verbose for CLI users.

**To Reproduce**
1. On windows or Linux, run the following `browser-history -b safari`. On MacOS, `browser-history -b chromium`.
2. See unnecessary traceback

**Expected behavior**

It should catch the exception and print only the error using `logger.error`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - `browser-history` Version: master
 - Python version: 3.8.5

**Additional context**

Thanks to @ObaraEmmanuel for finding the issue [here](https://github.com/pesos/browser-history/pull/123#issuecomment-765661530)

**Comment by anirudhRowjee** [comment]
could I work on this?

**Comment by Samyak2** [comment]
Sure!

**Comment by Samyak2** [comment]
Any updates?

**Comment by ObaraEmmanuel** [comment]
@Samyak2 I think we've allowed enough time for this. We should go ahead and fix it. I can get a patch ready by end of day

**Comment by Samyak2** [comment]
Thank you @ObaraEmmanuel. I'll assign the issue to you.

**Comment by ObaraEmmanuel** [comment]
The issue goes deeper than i thought. `utils.get_browser` returns the browser class regardless of whether it is implemented on the current system. I don't know if I should modify `utils.get_browser` to return `None` if browser is not implemented on current platform or create a new fucntion. The latter might add more stuff to utils which is not favorable and the former might break backwards compatibility.

**Comment by Samyak2** [comment]
> I don't know if I should modify `utils.get_browser` to return `None` if browser is not implemented on current platform or create a new fucntion.

I think we should do this. We can try including this change in `0.4.0` where we'll have some more breaking, but required, changes.

**Comment by ObaraEmmanuel** [comment]
so i should modify the functionality of `utils.get_browser` ?

**Comment by Samyak2** [comment]
Yes
