### ISSUE TITLE
[BROWSER] Support for Librewolf

### ISSUE THREAD

**Issue by OBITORASU** [pesos/browser-history#127]
**Describe the browser and provide any links if available**

Librewolf is a privacy oriented browser based on Librefox which in turn is based on Firefox.
Browser name: [Librewolf](https://librewolf-community.gitlab.io/)

**List the platforms supported by the browser to be added**
 Platforms:
 - [ ] Linux (#165)
 - [ ] Mac OS

**Additional Context**
Librewolf has become increasingly popular after Mozilla's controversial comments about free internet. Many Open Source/ Linux enthusiast have started switching to Librewolf as a Firefox alternative.

**Comment by Samyak2** [comment]
Do you want to take this up?

**Comment by OBITORASU** [comment]
I would prefer to keep this open and see if anyone new wants to contribute, else I might give it a shot myself.

**Comment by Samyak2** [comment]
Since no one else has taken this up yet, do you want to try?

**Comment by OBITORASU** [comment]
I did try to work on this somewhere back in April or May, but it took forever to compile librewolf on my Arch workstation via the AUR. I think I will skip on this one as testing might be an issue since compiling takes such a long time.

**Comment by Samyak2** [comment]
Oh damn, okay👍

**Comment by Agent-Hellboy** [comment]
working on this issue as part of the PyCon India 2021 sprint.

**Comment by Agent-Hellboy** [comment]
please check #165
