### ISSUE TITLE
[BUG] `utils.py` and `__init__.py` are ignored by codecov

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#128]
**Describe the bug**

Codecov only tracks 3 files in the `browser_history` module - `cli.py`, `browsers.py` and `generic.py` ([ref](https://codecov.io/gh/pesos/browser-history/tree/master/browser_history)). While these are the most important files of the project, a lot of code is also present in `utils.py`. This file is ignored by codecov ([ref](https://codecov.io/gh/pesos/browser-history/commit/8faf9855eefc6869232ae86a80173e33b664c66e)):

![image](https://user-images.githubusercontent.com/34161949/105805487-19730b80-5fc8-11eb-9b30-cb695ecd264e.png)

I tracked this down to an existing bug in codecov where it ignores files if a file of the same name is present in a different directory ([ref](https://community.codecov.io/t/bug-matching-filename-in-another-directory-cause-a-file-to-be-ignored/2256/1)). Since `tests/utils.py` and `tests/__init__.py` exist, `browser_history/utils.py` and `browser_history/__init__.py` are ignored.

Currently, there is no workaround for this bug in codecov ([ref](https://community.codecov.io/t/bug-matching-filename-in-another-directory-cause-a-file-to-be-ignored/2256/7?u=samyak)) except for renaming the files which is not a good solution.

**Expected behavior**

Codecov should track all the files inside `browser_history`

---

I've opened this issue to keep track of the upstream issue in codecov. If anyone finds any workaround for this, let me know!

**Comment by ObaraEmmanuel** [comment]
It's not even possible to rename `__init__.py` :laughing:

**Comment by Samyak2** [comment]
Look like it will be a while until it is fixed - https://community.codecov.io/t/bug-matching-filename-in-another-directory-cause-a-file-to-be-ignored/2256/11?u=samyak

**Comment by lucasace** [comment]
@Samyak2 https://community.codecov.io/t/bug-matching-filename-in-another-directory-cause-a-file-to-be-ignored/2256/12

You might want to check the above link

**Comment by Samyak2** [comment]
It's fixed! :tada:  `__init__.py` and `utils.py` show up in the directory ([example](https://codecov.io/gh/pesos/browser-history/tree/75c2b58602ea1e51bbfe906666840bbe78aaa34a/browser_history)).

But it looks like the coverage isn't very good on [`utils.py`](https://codecov.io/gh/pesos/browser-history/src/75c2b58602ea1e51bbfe906666840bbe78aaa34a/browser_history/utils.py).
