### ISSUE TITLE
Cannot open sqlite databases for Safari and Firefox when in Python 3.8 venv

### ISSUE THREAD

**Issue by FlxVctr** [pesos/browser-history#139]
**Describe the bug**
Cannot open sqlite databases for Safari and Firefox when in venv (created by Pipenv).

**To Reproduce**
1. Create pipenv with Python 3.8(.7/.9)
2. install browser-history
3. run `browser-history -b Firefox` or `-b Safari`
4. See error `sqlite3.OperationalError: unable to open database file`

**Expected behavior**
See the history.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - `browser-history` Version 0.3.0
 - Python version: 3.8.7

**Additional context**
Chrome works, Brave works in Python 3.8.9 and 3.9.4. Firefox and Safari work only in Python 3.9.4

**Comment by Samyak2** [comment]
That's weird. I'm not sure why pipenv would make it fail (although I have not used it before, so I'm not aware of the nuances of it). Could you try the following?

- close all open browser windows and run the tool only when there is no browser running in the background
- try the version from the current master branch. Command to install is [here](https://browser-history.readthedocs.io/en/latest/quickstart.html#installation)

browser-history creates a temporary directory to copy over the history files to it and then tries to open the file from there. Could it be related to storage space on your system?

**Comment by FlxVctr** [comment]
So I did some more digging, and the problem is apparently not the virtualenv, but might be with Python 3.8(.9, installed with pyenv and then used in pipenv). Pipenv with 3.9(.4) works. Sadly, for 3.9 there are install issues for another dependency I have in the project I am working on. Might there be something incompatible betweet 3.8's sqlite implementation and the Firefox DB?

**Comment by FlxVctr** [comment]
Storage is not an issue, btw.

**Comment by Samyak2** [comment]
> Might there be something incompatible betweet 3.8's sqlite implementation and the Firefox DB?

That could be a reason. Another culprit I could think of is [`tempfile.TemporaryDirectory()`](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) used [here](https://github.com/pesos/browser-history/blob/master/browser_history/generic.py#L265). It could be a permission issue with Mac OS. I have an older Mac OS system (Mojave) that I will test on later today or tomorrow.

We can rule out the SQLite issue if you could manually copy the `places.sqlite` file and run this through python (3.8):
```python
path = "<path to places.sqlite file here>"
conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
cursor = conn.cursor()
cursor.execute("SELECT * FROM moz_historyvisits")
```

Sorry about this issue :grimacing:, I'm not sure what's going wrong here either.

**Comment by Samyak2** [comment]
On Mac OS (Mojave), Firefox and Safari both work in a 3.7.3 installation. Will check on 3.8 through pipenv later.

**Comment by FlxVctr** [comment]
The code above runs smoothly in 3.8.9.

**Comment by FlxVctr** [comment]
Arrgh, actually it does not, sorry. Got lost in environments. But it also does not work with 3.7. So it seems to be something about my weird system.

**Comment by FlxVctr** [comment]
So, it works in a pipenv with 3.8.9, but not in my projects environment. So has to be some conflict with another package. Sorry for bothering you. Might not be a problem on your side. I'll investigate further, but feel free to close this,

**Comment by FlxVctr** [comment]
Sorry, have to correct myself again, it does not work in 3.8.9. Only if I opened it before with brew-installed 3.9.4 and the -wal and -shm files are still there. If I delete those, neither pipenv/pyenv-installed Python 3.8 nor 3.7 can execute the sqlite code above.

**Comment by Samyak2** [comment]
I did some more testing on the Mac OS system and was able to reproduce the issue on a pipenv environment with python 3.8.9.

The issue most likely is that the temporary directory made by `tempfile.TemporaryDirectory()` isn't writable by SQLite for some reason.

After scourging the [sqlite documentation](https://www.sqlite.org/uri.html), I found a potential fix that seems to work. I changed [this line](https://github.com/pesos/browser-history/blob/95d27f6497e876535ce1e8c86029ab7c780146ba/browser_history/generic.py#L268) to add a few more query parameters:

```python
conn = sqlite3.connect(f"file:{copied_history_path}?mode=ro&immutable=1&nolock=1", uri=True)
```

It works on the python 3.8.9 pipenv environment.

---

You can make changes to browser-history by cloning the repo into a separate directory and installing it in pipenv using `pipenv install -e <path to browser-history>`. Any changes you make in the directory will be reflected immediately when you run `browser-history` again.

---

I can open a PR for this later, or you can do it too if it works 😄

**Comment by FlxVctr** [comment]
The test script works with that adoption.
As does using the file path instead of the URI.
Is there a reason to open it in ro mode, except for good practice?

**Comment by Samyak2** [comment]
> The test script works with that adaptation.

Good to know!

> As does using the file path instead of the URI.

Do you mean it works without the `ro` flag?

> Is there a reason to open it in ro mode, except for good practice?

IIRC there was an issue on Windows without it, I don't remember now xD. Since we don't need write access, it works as a good practice.

**Comment by Samyak2** [comment]
The URI instead of file thing was added in the [first code commit](https://github.com/pesos/browser-history/commit/42533ac36fe87dc02b6a86b0f998b2406d7e999f), so I'm really not sure why it was added. If the tests work, we can consider reverting it to just the file path.

**Comment by FlxVctr** [comment]
Already gone with the URI for the PR

**Comment by FlxVctr** [comment]
But feel free to change anything or to scrap it.

**Comment by FlxVctr** [comment]
> I tested it and can confirm this. I'm not sure why it behaves this way. Do you have any idea?

macOS being funny with its pre-installed sqlite3 binary (most likely outdated). Or requiring something like 'Full Disk Access' permissions. But tbh, really no clue.

**Comment by Samyak2** [comment]
> macOS being funny with its pre-installed sqlite3 binary (most likely outdated). Or requiring something like 'Full Disk Access' permissions.

Ah okay, that makes sense. Does it mean that python uses that binary internally? Since the sqlite3 module is supposed to be a C implementation of sqlite, I don't know if having it depend on the binary makes sense.

**Comment by FlxVctr** [comment]
I'd think it simply uses the binary it finds on your PATH first. But just guessing here, don't know the sqlite package except for using it. Thanks for merging the PR. When would you expect the next release on PyPI? (Asking to decide whether it makes sense to wait or to find out how to git install in beeware).

**Comment by Samyak2** [comment]
I was planning to make a release soon, but that will take a couple of days. The earliest I can do is tomorrow night (that is 20-24 hours from now). Let me know if that works.

**Comment by FlxVctr** [comment]
No rush, project is in early stages. Just checking feasibility.

**Comment by Samyak2** [comment]
Haha, that's okay. A release has been overdue for a while now. There have been around 10-15 PRs since the last release.

**Comment by Samyak2** [comment]
I've made a new release ([v0.3.1](https://github.com/pesos/browser-history/releases/tag/v0.3.1)). Let me know if this fixes your issue and sorry for the delay!

**Comment by FlxVctr** [comment]
Already worked with the github version. Seems to work now also with the Pypi version. Thanks! And no worries. Not a paying customer ;)

**Comment by Samyak2** [comment]
Good to know!
