### ISSUE TITLE
[DOC] contributing guidelines are missing `python-dateutil` dependency install

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#142]
# The Issue

The [contributing guidelines](https://browser-history.readthedocs.io/en/latest/contributing.html) (the file can be found [here](https://github.com/pesos/browser-history/blob/master/docs/contributing.rst)) have missed a development dependency in the 1st section, 2nd point.

The missing package is `python-dateutil`, without which the tests will fail.

# Solution

Add `python-dateutil` to that pip install command and also list it along with the other dependencies, specifying what it's used for. The `python-dateutil` package is used to resolve timezone-related issues in the tests (from #94).

---

This issue was pointed out in #141, thank you @FlxVctr.

**Comment by avnish100** [comment]
hey! can i work on this?

**Comment by Samyak2** [comment]
Sure!
