### ISSUE TITLE
[BUG] Publish workflow won't trigger correctly if release is first drafted

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#148]
**Describe the bug**
If you draft and save a release first before publishing it, trying to publish it later will not trigger the pypi publish workflow. Its because it's using `type: [created]` instead of the better trigger `type: [published]`

**To Reproduce**
1. Draft a release
2. Save the draft release
3. Publish the release

**Expected behavior**
Release should be uploaded to pypi

**Additional context**
Noticed this in one of my other projects thought I should raise it up here as well

**Comment by Samyak2** [comment]
I had not tried drafting a release yet. Thank you for opening this issue!

**Comment by nerdishhomosapein** [comment]
I am working on this issue.
