### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#161]
browser-history will soon be moved to a brand new organization (https://github.com/browser-history). We'll need a logo for it.

## Requirements

Doesn't have to be anything fancy, even a simple one will do.

A square-ish image will be ideal for the organization logo.

---

You will be credited in the README, in the docs and wherever else the logo will appear :heart:

**Comment by xames3** [comment]
What do you think of this? Made a quick one in Photoshop.
![browser-history](https://user-images.githubusercontent.com/90549089/134705259-a6404c2f-c3d0-4765-8e26-06936d743d63.png)

**Comment by Samyak2** [comment]
@xames3 that looks quite good! Thank you :heart: 

Do you mind sending a PR adding this logo (a `logo.png` in the root folder will do) and adding yourself in the README (make a "Credits" section just before the license)?

Also, could you confirm that none of the graphics used are copyrighted?

**Comment by xames3** [comment]
> 
> 
> @xames3 that looks quite good! Thank you ❤️
> 
> Do you mind sending a PR adding this logo (a `logo.png` in the root folder will do) and adding yourself in the README (make a "Credits" section just before the license)?
> 
> Also, could you confirm that none of the graphics used are copyrighted?
> 
> Sorry for the late reply.

I've made some minor modifications to the original one.

![browser-history](https://user-images.githubusercontent.com/90549089/134768716-67ee6185-10c0-4358-aaf1-5b91cc05b395.png)

Thanks for giving the credit! :heart: I've raised a PR for the same, also I confirm that no graphic used here were copyrighted and are made from scratch. Here's the PSD file ([browser-history-logo.zip](https://github.com/pesos/browser-history/files/7229601/browser-history-logo.zip)) for your reference. Please keep it around in case someone wants to change it in future.
