### ISSUE TITLE
[FEATURE REQ] ASCII art in CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#162]
**Is your feature request related to a problem? Please describe.**

The CLI `--help` section is a little boring

**Describe the solution you'd like**

Add browser-history ASCII art in the CLI description. An example of what the ASCII art can look like: https://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=browser-history (it must be readable).

It will have to be added here:

https://github.com/pesos/browser-history/blob/master/browser_history/cli.py#L29

**Comment by aayush-jaiswal** [comment]
I will work on this
