### ISSUE TITLE
[DOC] Update copyright year

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#169]
**Is your feature request related to a problem? Please describe.**

The [documentation](https://browser-history.readthedocs.io/en/latest/) footer still says `2020`

**Describe the solution you'd like**

Change 2020 to 2021 here:
https://github.com/pesos/browser-history/blob/4c81575fa2e1404952aa7bc465553492ea902074/docs/conf.py#L22

**Comment by Simba-97** [comment]
Hey @Samyak2 I would like to do a PR on this issue.

**Comment by MuckHub** [comment]
@Samyak2 Can I work on this one please? First time for me :)

**Comment by Kalingrowo** [comment]
thank you for the issue ( clues ), 
i get the gist of pull request on public repo

**Comment by Samyak2** [comment]
Closed via #170
