### ISSUE TITLE
[BUG] Errors in documentation

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#17]
**Describe the bug**

 - Grammar mistake in the main page
![image](https://user-images.githubusercontent.com/34161949/93591439-fad38700-f9cd-11ea-9deb-5192b64e932c.png)
 - The doc for `browsers.Chromium` says "Google Chrome"
![image](https://user-images.githubusercontent.com/34161949/93591531-32daca00-f9ce-11ea-9573-7445a9832afc.png)
 - (Not an error or a bug) the quick start could demonstrate the use of `browser_history.get_history` from #15.

**To Reproduce**

1. Go to [the documentation](https://browser-history.readthedocs.io/en/latest/index.html)
2. Read
3. Scroll?

**Expected behavior**

The errors need to be fixed and an example usage of `get_history()` must be included in the quick start.

**Additional context**

If you find any more errors, add them to the thread here.

**Comment by sujanchegu** [comment]
I'll work on this.

**Comment by Samyak2** [comment]
Sure.
