### ISSUE TITLE
[FEATURE REQ] Case in-sensitive browser name matching in CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#20]
**Is your feature request related to a problem? Please describe.**

Currently the CLI (#16) only matches browsers based on the exact class name (Ex: `Chrome`, `Firefox`)

**Describe the solution you'd like**

CLI should be able to identify and match in a case-insensitive manner. For example:
```bash
browser-history -b firefox
```
should be the same as
```bash
browser-history -b Firefox
```

**Describe alternatives you've considered**

Could do fuzzy matching based on the `name` field of the browsers, but case insensitive matching seems simple and good enough for most purposes.

**Additional context**

#16 needs to be merged before this.

**Comment by MadhavJivrajani** [comment]
Hi!
Can I work on this?

**Comment by Samyak2** [comment]
Go ahead!

**Comment by MadhavJivrajani** [comment]
@Samyak2 just to be sure, I make changes to ensure that the parameter passed in [this](https://github.com/pesos/browser-history/blob/d4e2ea4738758bfdb0bc1b780b6b27bdf1255f4e/browser_history/cli.py#L47) line is case insensitive right?

**Comment by Samyak2** [comment]
Yes
