### ISSUE TITLE
[TESTS] Need more tests!

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#22]
# The issue

Current code [test coverage](https://codecov.io/gh/pesos/browser-history) is around ~~65%~~ 88% which may not seem too bad, but the actual situation is worse.

The tests are currently only for Firefox on Linux. 😬

# Required tests

**Browsers**

|                   | Platform | Linux | Mac | Windows |
|----------------|------------|---------|--------|---------|
| Browser     |              |           |          |         |
| Firefox       |              | ✅      |  ❌     | ❌    |
| Chrome     |              |  ❌     |  ❌     | ❌    |
| Chromium |              |  ❌     |  ❌     | ❌    |
| Safari        |              |  ⬜     |  ✅      | ⬜    |
| Edge        |              |  ⬜     |  ❌     | ✅    |
| Opera     |              |  ❌     |  ❌     | ✅    |
| Opera GX        |              |  ⬜     |  ⬜      | ✅    |
| Brave     |              |  ❌     |  ❌     | ❌    |

**CLI**

~~There are no tests are CLI currently.~~

See #65 

**generic.py**

Domain history is not tested. Refer the [codecov report](https://codecov.io/gh/pesos/browser-history/src/master/browser_history/generic.py)

# Writing Tests

Refer [this section](https://browser-history.readthedocs.io/en/latest/contributing.html#tests) in the contributing guidelines

**Comment by ObaraEmmanuel** [comment]
I can add tests for Firefox in windows

**Comment by sujanchegu** [comment]
Absolutely! Go ahead. If you need any help, Contact us here or on tbe slack channel. The Maintainer will assign you shortly.

**Comment by Samyak2** [comment]
Sure! I can't assign you here since this is a general issue, but please go ahead and send a PR.
Thank you.

**Comment by sujanchegu** [comment]
@Samyak2 Add the new browsers(Opera, OperaGX etc) to the checklist in the PR Template.

**Comment by ObaraEmmanuel** [comment]
@Samyak2 I realize the workflows you have written only run on ubuntu so you could not realize that after merging PR #39 tests are now failing on Windows. In fact, this particular PR breaks browser-history on Windows altogether. Please try running the tests on Windows and see what I am talking about.

**Comment by Samyak2** [comment]
@ObaraEmmanuel yes, I tried running it on windows and it failed :grimacing:. It is due to the path separator being hardcoded. Can you open a separate issue for this?
Also I did not realize that GitHub actions supported platforms others than Ubuntu. I will open another issue for that. This should prevent future issues like these.

Thank you for reporting this!

**Comment by ObaraEmmanuel** [comment]
Yes, i will open an issue for that ASAP.

**Comment by gillesigot** [comment]
I can add tests for Chrome on Linux.

**Comment by sujanchegu** [comment]
Hey! Go ahead! Since it's already been said in previous comments, the issue can't be explicitly assigned to you since it's a general issue. Direct your PR to the master branch.


@Samyak2 you have to add Brave and newly added browsers to the list.

**Comment by Samyak2** [comment]
> @Samyak2 you have to add Brave and newly added browsers to the list.

Done!

**Comment by gillesigot** [comment]
Hey, I just added some testing for **generic.py**.  I see that **utils.py** is missing some coverage, I can also work on it if that's ok?
