### ISSUE TITLE
Sort histories after retrieving

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#3]
Histories for individual profiles are sorted, but when combining histories from multiple profiles they are simply concatenated.

# Required features

 - Sort histories based on the timestamp (first value in the tuples) after concatenating. If you have any other ideas to go about this, feel free to comment.
 - Add a `sort` parameter to the `history` method.

# Related code

https://github.com/Samyak2/browser-history/blob/49bc1f16cb41f772c553c6768ea66116ec43cbfd/browser_history/generic.py#L155

**Comment by sujanchegu** [comment]
Can I work on this issue?

**Comment by Samyak2** [comment]
Sure, @sujanchegu go ahead!
