### ISSUE TITLE
[ENHANCEMENT] Removal of TODO comment

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/browser-history#30]
Hi,
I forgot to remove the `TODO` [comment](https://github.com/pesos/browser-history/blob/b371317d51812068c7e6c32b2a16fead62aba185/browser_history/cli.py#L46) while sending in PR #21 

Maybe a `first-timers-only` issue?

**Comment by sachmo99** [comment]
hey there! Can you assign this to me? I wish to submit a PR under first-timers-only section (This would be my first PR to a public repo of open source :) )

**Comment by Samyak2** [comment]
Go ahead! Let us know if you need any help (either here or on the [slack](https://pesos.github.io/get-started/communication-channels)).
Also, I would suggest going through the [contribution guide](https://browser-history.readthedocs.io/en/latest/contributing.html) (at least the short version)

**Comment by sachmo99** [comment]
Yeah sure. Thanks a lot! Can I start on Oct 1? for the hacktoberfest :)

**Comment by sujanchegu** [comment]
Yeah No problem

**Comment by sumana-19** [comment]
Hello, can you assign this to me? I'd like to work on this issue.
Thanks.

**Comment by MadhavJivrajani** [comment]
Hi @sumana-19 ,
Thank you for your interest in contributing! This issue is already assigned to @sachmo99 , we'll let you know if anything changes!

In the meantime please feel free to let us know if we can help you out in any way should you be interested in working on any of the other issues that have been put up! 😄
