### ISSUE TITLE
[BUG] Browser.profiles() returns only the directory name

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#31]
**Describe the bug**

In `generic.Browser`, the `profiles()` function returns only the last part of the path (the directory name).
For example, if a browser has profiles stored as such: `profiles/profile1`, `profiles/profile2`, etc. `profiles()` will return `["profile1", "profile2"]` which will fail in `fetch()` since the intermediate directory is missing.

This does not affect any of the existing browsers, but it's a bug that needs to be addressed before such a browser is added.

**To Reproduce**

Run the following code from the directory of this repo. 

```python
from browser_history.generic import Browser
from pathlib import Path

# to ensure that it looks in the current dir instead of home dir
Path.home = lambda: Path(".")

class SomeBrowser(Browser):
    name = "Non-existent browser"

    windows_path = "./tests/test_homedirs/Linux/.mozilla/"
    mac_path = "./tests/test_homedirs/Linux/.mozilla/"
    linux_path = "./tests/test_homedirs/Linux/.mozilla/"

    profile_support = True
    profile_dir_prefixes = ["*/*"]
    history_file = "places.sqlite"

s = SomeBrowser()
print(s.profiles())
print(s.history_paths())
print(s.fetch()) # Error
```

It fails with an error since the intermediate directory `firefox` was not returned by `profiles()`

**Expected behavior**

`profiles()` should return the entire *relative* path from `history_dir` instead of just the last directory name.

**Additional context**

Related code:

https://github.com/pesos/browser-history/blob/b371317d51812068c7e6c32b2a16fead62aba185/browser_history/generic.py#L85-L101

**Comment by lucasace** [comment]
Can I get assigned to this?

**Comment by Samyak2** [comment]
Sure!

**Comment by lucasace** [comment]
I fixed this issue but this brings up the following bug while running 
```bash
from browser_history import get_history
outputs = get_history()
google-chrome/Default
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/royston/Documents/browser-history/browser_history/__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "/home/royston/Documents/browser-history/browser_history/generic.py", line 165, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/royston/.config/google-chrome/google-chrome/Default/History'
```
I printed out the value in profile_dirs  to show what I did
Can you check this out and tell me ??

**Comment by Samyak2** [comment]
Can you open a draft PR from your branch so I can checkout the code?

**Comment by lucasace** [comment]
PR opened
