### ISSUE TITLE
[BROWSER] Opera support

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#32]
## Describe the browser and provide any links if available

Browser name: [Opera](https://www.opera.com/hi)

Opera is based on Chromium, so it should be easy to add support for it given you find the history location. The `history_SQL`, `history_file`, etc. can be set to be the same as Chrome/Chromium. Look at the implementation of Edge for ideas (#24)

## List the platforms supported by the browser to be added

 Platforms:
 - [x] Windows
 - [x] Linux
 - [ ] Mac OS

**Comment by LawJarp-A** [comment]
Hey, I'd like to work on this issue

**Comment by sujanchegu** [comment]
Yes! Go ahead. Any idea on what platforms you want to add support for? This helps us in assigning the remaining ones to anybody else. Also, If you need any help, Contact us here or on our slack channel.

**Comment by LawJarp-A** [comment]
> Yes! Go ahead. Any idea on what platforms you want to add support for? This helps us in assigning the remaining ones to anybody else. Also, If you need any help, Contact us here or on our slack channel.

Linux and windows, though there seems to be a problem with path, if opera is installed with snap store directly in linux

**Comment by sujanchegu** [comment]
Samyak, the maintainer will assign it to you shortly.

**Comment by Samyak2** [comment]
> Linux and windows, though there seems to be a problem with path, if opera is installed with snap store directly in linux

Is the path different when installed through snap?

**Comment by LawJarp-A** [comment]
> > Linux and windows, though there seems to be a problem with path, if opera is installed with snap store directly in linux
> 
> Is the path different when installed through snap?

In Ubuntu, yes, installing Opera through the store puts the folder in snaps folder, not sure if that's the case for only Opera or other Browsers too

**Comment by Samyak2** [comment]
> In Ubuntu, yes, installing Opera through the store puts the folder in snaps folder, not sure if that's the case for only Opera or other Browsers too

That's a tricky case. Is the snaps folder under the user's home directory or somewhere else?

**Comment by LawJarp-A** [comment]
> > In Ubuntu, yes, installing Opera through the store puts the folder in snaps folder, not sure if that's the case for only Opera or other Browsers too
> 
> That's a tricky case. Is the snaps folder under the user's home directory or somewhere else?

Yes, its /home/user/snaps

**Comment by Samyak2** [comment]
Mac OS support is yet to be added, re-opening this if anyone wants to work on it.

**Comment by sujanchegu** [comment]
@Samyak2 Remove the assignee so that it appears to a unassigned issue.
