### ISSUE TITLE
[BROWSER] Opera GX Support

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#33]
## Describe the browser and provide any links if available

Browser name: [Opera GX](https://www.opera.com/hi/gx)

Opera GX is based on chromium, so it should be easy to add support for it. Take a look at the implementation of Edge (#24) for ideas.

## List the platforms supported by the browser to be added
Platforms:
 - [ ] Windows

**Comment by rahulmakhija30** [comment]
Could I work on this?

**Comment by Samyak2** [comment]
Sure.
