### ISSUE TITLE
[FEATURE REQ] Export outputs to CSV

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#34]
**Is your feature request related to a problem? Please describe.**

Currently, the outputs are a tuple of urls and timestamps. It would be useful to have an option to export this data to a readable file such as CSV.

**Describe the solution you'd like**

A function in `generic.Outputs` called `to_csv` that exports the history to the given filename in CSV format.

**Describe alternatives you've considered**

Other issues are opened for alternate formats (if you can't find an issue for the format you need, please open one)

**Additional context**

This has been partially implemented in #27.

**Comment by ObaraEmmanuel** [comment]
Hello, I would like to begin my contribution to your project through this issue. I was thinking, what if we have cli arguments to specify the formats (whether CSV, JSON or YAML) and separate arguments to specify output to file. This will make it possible to display for instance JSON format directly on the command line without needing to output to file unless the output to file arguments have been provided. That's my take and I would like to know what you think about it.

**Comment by Samyak2** [comment]
Hi, that's a good idea! Can you suggest/copy this idea to #6, I feel it belongs there and people looking to contribute to that issue will get an idea on how to go about it.
There's a PR already for #6, but there hasn't been much activity on it, you're welcome to try and fix both this issue and #6.

**Comment by ObaraEmmanuel** [comment]
I can fix both issues.

**Comment by Samyak2** [comment]
Sure! Thank you.

Just to confirm, by both issues you mean this and #6?

**Comment by tanya4067** [comment]
hey, I'd like to contribute

**Comment by Samyak2** [comment]
Hey @tanya4067, sorry this issue was taken by @ObaraEmmanuel and he has already sent a PR for it. Take a look at the other issues.
