### ISSUE TITLE
[FEATURE REQ] provide option to export in readable and platform independant formats

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/browser-history#4]
It would be helpful if the browser histories could be exported (optionally) or displayed in a user-specified, more readable format like `json` or `csv` as opposed to a list of `datetime.datetime, url` tuples. 

Please let me know if I'm missing anything or if this was done by design :smile:

**Comment by sujanchegu** [comment]
- Adding label `good-first-issue` would be helpful to beginners.
- Methods Fixing this issue are expected to be added to browser_history.generic.Outputs

**Comment by Addilergy** [comment]
hi, I had a question, how would you want the Json object structure to look like?
The idea I had in mind is
```
date:
        [
            {
                time: Time
                url: URL
            },
            {
                time: Time
                url: URL
            }, ....
        ]
```
just confirming if this is a good idea

**Comment by Samyak2** [comment]
@nihal-ramaswamy that looks good. I can think of two ways to do this.

 - [JSON lines](https://jsonlines.org/): Here, each line in the file will be a JSON with time and URL, similar to a CSV file.
   ```jsonl
   {"time": "time1", "url": "url1"}
   {"time": "time2", "url": "url2"}
   ```
 - Plain JSON: This would allow us to have some metadata such as browser name, platform, etc. in the exported file. Something like this
   ```json
   {
     "browser": "Firefox",
     "platform": "Linux",
     "history": [
        {
            "time": "time",
            "url": "url"
        },
        {
            "time": "time2",
            "url": "url2"
        }, ...
     ]
   }
   ```
   For this, the metadata will have to be added in `browser_history.generic.Outputs` from #14.

**Comment by sujanchegu** [comment]
I work on this?

**Comment by nihal-ramaswamy** [comment]
idk, probably will start soon

**Comment by Samyak2** [comment]
I think it's better to open separate issues for each format (CSV, JSON, YAML, etc), this will help contributors better understand what's required to be done.
