### ISSUE TITLE
[BROWSER] Brave support

### ISSUE THREAD

**Issue by siddhantrao23** [pesos/browser-history#42]
**Describe the browser and provide any links if available**
Browser name: [Brave](https://brave.com/)
Implementation would be very similar to Chrome/Chromium as brave has now moved to chromium, but with a slightly different history path.

**List the platforms supported by the browser to be added**
- [ ] Windows
- [x] Linux
- [ ] Mac OS

**Comment by Samyak2** [comment]
Since Brave is also available for Windows and Mac, I'll keep this issue open even after merging #66
