### ISSUE TITLE
[BUG]Incomplete fetching of history in Firefox

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#43]
**Describe the bug**
When fetching history for Firefox with `browsers.Firefox().fetch().get()`, only partial history is returned. Sometimes, nothing is returned. I noticed this when I was writing tests for Firefox on Windows. I cleared my browser history and went to five different sites but on fetching nothing was returned. Fortunately, In the process, I was also able to trace the source of the bug to the `history_SQL` attribute of `Firefox` class.

**To Reproduce**
Open the history snapshot [places.qslite](https://github.com/pesos/browser-history/blob/master/tests/test_homedirs/Linux/.mozilla/firefox/profile/places.sqlite) (used in testing Firefox for linux) using any SQL browser and run the query used to retrieve the history. Only one match is returned but if you inspect the `moz_historyvisits` table you realize there are actually 5 history visits
![Query_incorrect](https://user-images.githubusercontent.com/36537378/94815933-c61af300-0403-11eb-9183-67b004fe9a16.png)

**Expected behavior**
There should be 5 history visits for this particular snapshot that meet the query constraints as shown by the correct query below.
![Query_correct](https://user-images.githubusercontent.com/36537378/94815370-1e9dc080-0403-11eb-8b56-ddc28a221fb0.png)

**Possible fix**
The two columns being joined `moz_historyvisits.place_id` and `moz_places.id` have different names hence a `NATURAL JOIN` just doesn't work. Replacing `NATURAL JOIN` with `INNER JOIN ON moz_historyvisits.place_id = moz_places.id` seems to work. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - `browser-history` Version: v0.2.1
 - Python version: 3.8.0

**Comment by ObaraEmmanuel** [comment]
I can have a patch for this ready in a few minutes

**Comment by Samyak2** [comment]
Thank you for reporting this! That explains some inconsistencies I found when writing the tests for firefox on linux.
I'll assign you right away
