### ISSUE TITLE
[BUG] Mac OS safari Permission Error

### ISSUE THREAD

**Issue by abhisinha2001** [pesos/browser-history#56]
**Describe the bug**
When I run the get_history() function I get the following error on my Mac.
``` bash 
outputs = get_history()
INFO: Chromium browser is not supported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/abhinavsinha/Development/git/git2/browser-history/browser_history/__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "/Users/abhinavsinha/Development/git/git2/browser-history/browser_history/generic.py", line 170, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/Users/abhinavsinha/Library/Safari/History.db'
```
**To Reproduce**
Run the following code on Mac Terminal:
```bash
from browser_history import get_history
outputs = get_history()
```

**Expected behavior**
Should produce the history for safari browser

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [safari]
 - `browser-history` Version [e.g. v0.1.1, master]
 - Python version: [e.g. 3.8.3]

**Comment by Samyak2** [comment]
Which version of Mac OS are you on (Mojave, Catalina, etc)?

**Comment by abhisinha2001** [comment]
The version is Catalina.
It may not be a Catalina specific issue as it was running perfectly a couple of commits before.

**Comment by Samyak2** [comment]
I cannot reproduce this error on Mojave even when Safari is running.
Can you if the history file is accessible or if it exists?

**Comment by abhisinha2001** [comment]
Sure will look into it.

**Comment by Samyak2** [comment]
Did this get fixed?

**Comment by Lyro1** [comment]
Hello. Just to do a quick follow-up there:

This issue is not fixed. I am under **macOS Catalina 11.0.1**, and the database file exists and seems to be correct. However, I can't access it from the terminal, even a `sudo cat /Users/my-username/Library/Safari/History.db` raises an `Operation not permitted` error...

**Comment by Lyro1** [comment]
Just found the solution for me: the terminal did not have full-disk access. Just open your Settings > Security > Confidentiality > Full-disk access and check the box for terminal. Close the terminal and open again, this should do the trick !
