### ISSUE TITLE
[BUG] Fetching history failing on Windows

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#58]
**Describe the bug**
History fetching fails almost completely on windows after commit e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4 .

**To Reproduce**
Run the following code at the terminal
```python
from browser_history import get_history
output = get_history()
```
This raises the following errors
```python
Traceback (most recent call last):
  File "C:\Users\MANU\OneDrive\Projects\browser-history\runner.py", line 5, in <module>
    main()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\cli.py", line 55, in main
    outputs = get_history()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "C:\Users\MANU\OneDrive\Projects\browser-history\browser_history\generic.py", line 170, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "C:\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MANU\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History\\History'
```

**Expected behavior**
This should return history for all installed browsers but instead this error is thrown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - `browser-history`: master branch e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4
 - Python version: 3.8.0

**Additional context**
This issue can be traced back to PR #39 . The cause is probably due to hardcoding of path separators.

**Comment by lucasace** [comment]
Really sorry for this, the problem arised because glob according to https://docs.python.org/3/library/glob.html is based on unix pattern matching thus explaining the success for Linux and MAC-OS, I should have checked for windows as well,
Ill give it a fix as it arised from my PR

**Comment by ObaraEmmanuel** [comment]
No problem, once the workflows are updated to include windows and macOS, such problems can be avoided.

**Comment by lucasace** [comment]
@Samyak2 I fixed this and tested this on a windows system and it works , but before i set up a PR, I have a error arising due to the opera class
If I have never installed opera , and run the following code
```bash
from browser_history import get_history
outputs = get_history()
```
then I get the following error 
```bash
INFO: Safari browser is not supported
INFO: Edge browser is not supported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/royston/Documents/browser-history/browser_history/__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "/home/royston/Documents/browser-history/browser_history/generic.py", line 173, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/royston/.config/opera/History'

```
I am not sure why this arises, so just wanted to report this

**Comment by Samyak2** [comment]
@lucasace can you open a new issue for it? It's a valid problem that arises because we're only ignoring `AssertionError` in `get_history`. It needs to be fixed ASAP.

**Comment by lucasace** [comment]
sure!
