### ISSUE TITLE
[FEATURE REQ] Export options in CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#6]
# Description

Add CLI flags to export the data into a file in different formats (such as JSON, CSV, etc).

# Implementation

#4 and #5 must be closed before starting work on this.

Some ideas for the flags:
 - `-e`, `--export`: Including this flag should export it in a default format and an optional value for export format.

**Comment by ObaraEmmanuel** [comment]
**Additional suggestions**

- optional flags `-f, --format` to specify the output format (CSV, JSON, YAML and any other implementation). Based on current implementation and for the sake of backward compatibility the default format is CSV. The  arguments should of course be case insensitive.

- optional flags `-o, --output` to specify the file to which the history data is to be written. If not provided the output is displayed on the console
