### ISSUE TITLE
[BUG] Error arrises for uninstalled browsers

### ISSUE THREAD

**Issue by lucasace** [pesos/browser-history#60]
**Describe the bug**
If the user has never installed a particular browser on his OS, then despite not having the browser, the package still tries to find the history file for that browser. A Example would be, if the user is using Linux as his OS and has not installed opera till date, then on running it raises the error,
```bash
INFO: Safari browser is not supported
INFO: Edge browser is not supported
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/royston/Documents/browser-history/browser_history/__init__.py", line 20, in get_history
    browser_output_object = browser_object.fetch()
  File "/home/royston/Documents/browser-history/browser_history/generic.py", line 173, in fetch
    copied_history_path = shutil.copy2(history_path.absolute(), tmpdirname)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/royston/.config/opera/History'
```
**To Reproduce**
To reproduce with opera browser, uninstall opera and remove all its corresponding files
Linux : remove .config/opera
Windows : remove AppData/Roaming/Opera Software/Opera Stable

and run the following code:
```bash
from browser_history import get_history
output = get_history()
```
**Expected behavior**
Should state , the browser is not installed 

**Desktop (please complete the following information):**
 - OS: [Linux]
 - `browser-history` Version [master]
 - Python version: [e.g. 3.8.3]

**Additional context**

This error can occur with any browser as long as its never been installed but is comaptible for that OS

**Comment by Samyak2** [comment]
The fix involves adding another except statement near [this](https://github.com/pesos/browser-history/blob/e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4/browser_history/__init__.py#L22) for `FileNotFoundError` and logging a appropriate message inside it.

**Comment by ObaraEmmanuel** [comment]
Is anyone handling this one or should I go ahead?

**Comment by ObaraEmmanuel** [comment]
> The fix involves adding another except statement near [this](https://github.com/pesos/browser-history/blob/e00280bcbaa5550b2e3b3f2fd6a9c3a2128775a4/browser_history/__init__.py#L22) for `FileNotFoundError` and logging a appropriate message inside it.

I have realized there is more to the fix than just this. Your suggested only works when fetching all browsers but when i do something like `browser-history -b opera` in the CLI it still throws that error.
There are two options:

1. Catch the error in `get_history` as well as in [cli.py](https://github.com/pesos/browser-history/blob/62a2427d67cb462bd23717cb83085eb37d0b69e8/browser_history/cli.py#L66)
2. Catch the error inside `generic.Browser.fetch`, log the absence of the browser and return an empty list

**Comment by Samyak2** [comment]
@ObaraEmmanuel you are right, I didn't think of that.

I like the 2nd option as it saves repetitive code and that behaviour of the function is expected. (This should be documented in the docstring though)

**Comment by ObaraEmmanuel** [comment]
On further digging, I have realized the best place to catch the error is actually in the `generic.Browser.profiles` method. Every other method seems to be starting from here and even when we come to implement functionality for cookies and bookmarks they will most likely begin with determining profiles.
