### ISSUE TITLE
[DOC] Document Outputs class

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#63]
## Issue

The `generic.Outputs` class is not documented in the docs yet. Considering that this contains functions to export histories to various formats, it is an important class that has to be documented.

Also, the docstrings in that class have some formatting issues that will make the docs build fail. These have to be fixed.

## Describe the solution you'd like

 - A new file `docs/outputs.rst` which contains some brief about what this class is for and the rest should be from the docstrings.
 - Add `outputs` under `API.rst`
 - Fix docstring issues
 - Ensure the documentation looks good

## Additional context

Look at `functionality.rst` and `utils.rst` for ideas.

**Comment by rachmadaniHaryono** [comment]
hi, i'm interested in this issue so i make #75, which is still wip
