### ISSUE TITLE
[TESTS] add tests for CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#65]
## Is your feature request related to a problem? Please describe

The entire `cli.py` module is not covered by any tests. It is important to test the parser behaviour and the expected outputs to ensure that the CLI does not break.

## Describe the solution you'd like

 - Refactor the CLI `cli.main()` function to accept a list of arguments as input instead of taking the args from `sys.argv` directly. ([reference](https://stackoverflow.com/a/18161115/11199009))
 - A new module under `tests/` named `test_cli.py` that contains test functions/classes for the CLI.
 - Ensure that the tests run and pass.

**Comment by sadielbartholomew** [comment]
Hi, I'd like to take on this Issue as part of Hacktoberfest if that is okay and it is not already assigned to someone externally. Would you be happy to assign me, and accept my contribution as a Hacktoberfest PR should I manage to put in a PR that closes it?

If so, the summary here is very clear so I understand exactly what is wanted. Just to check one aspect though, based on the reference in the comment, it seems you want a solution for the refactor based on the `argparse` module. Is that correct?

Thanks.

**Comment by Samyak2** [comment]
> Hi, I'd like to take on this Issue as part of Hacktoberfest if that is okay and it is not already assigned to someone externally. Would you be happy to assign me, and accept my contribution as a Hacktoberfest PR should I manage to put in a PR that closes it?

@sadielbartholomew Hi. Sure! Thank you.

> If so, the summary here is very clear so I understand exactly what is wanted. Just to check one aspect though, based on the reference in the comment, it seems you want a solution for the refactor based on the `argparse` module. Is that correct?

Yes, that is correct. The CLI code uses the `argparse` module.

**Comment by sadielbartholomew** [comment]
Thanks @Samyak2. I expect to be able to put in a PR for this by the end of this weekend, possibly sooner. If I am otherwise busy so that it ends up taking longer I will let you know.

**Comment by Samyak2** [comment]
Sure, no hurries.

**Comment by Samyak2** [comment]
@sadielbartholomew any updates?

**Comment by sadielbartholomew** [comment]
Hi, I ended up being busier than I expected, but I will prepare the PR over the weekend and put it in on Monday. I will still get it done. Sorry for the delay,.

**Comment by Samyak2** [comment]
@sadielbartholomew no issues. Just wanted to know if you were still doing it.
Thank you.

**Comment by sadielbartholomew** [comment]
Hi, just to update you, I will be a bit later still with this but I shouldn't take longer than a couple more days to get the PR up. Mainly I am late with it because when I started working on it yesterday I got distracted with some test failures (as raised in #90).

**Comment by sadielbartholomew** [comment]
Hi again, just to provide an update, I've missed the chance to complete the PR for this for Hacktoberfest because I was busier than I thought over the weekend, but I still plan to address it.

The unit test is done, so I just need to do the refactor of the CLI to us `argparse` and I am not far from finishing that. However, I am very busy until tomorrow afternoon (my time, UK) so it will be towards the end of the working week when I can put in the PR. I hope that is okay. Sorry for the delay. Thanks.

**Comment by Samyak2** [comment]
That is okay. Thank you for updating

**Comment by Samyak2** [comment]
Any updates?
I wanted to have these tests ready for the 0.3.0 release. So if you have any progress on this, feel free to open a draft PR so I can take a look and contribute to it.

**Comment by sadielbartholomew** [comment]
Ah, very sorry @Samyak2 this fell off my radar. I'll try to finish tonight but regardless I will put up a PR, draft or otherwise. Thanks.
