### ISSUE TITLE
[BUG] Spurious history records when fetching from chromium based browsers

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#71]
**Describe the bug**
Fetching history from chromium based browsers or at least for Opera on windows returns spurious and duplicate records. Some of these URLS are split second redirects that cannot be considered as visits. Once again the SQL query used is faulty and these time its affecting more browsers. I am not sure if other browsers other than opera are affected so it would be prudent to inspect them as well. 

**To Reproduce**
1. Clear your Opera browser history
2. Visit any sites and take note. Do not include the scheme so as to simulate the redirects I am talking about. For instance, visit [github.com](github.com) instead of [https://github.com](https://github.com)
3. Try fetching using the usual `browser-history -b opera`

**Expected behavior**
In my case there were only 5 valid visits
![chromiumQueryCorrect](https://user-images.githubusercontent.com/36537378/95837193-fee29280-0d48-11eb-9371-0e3d86c2a70a.png)
But here is the spurious output
![chromiumQueryInCorrect](https://user-images.githubusercontent.com/36537378/95837291-1de12480-0d49-11eb-8ab9-ed7c1d411a1d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera
 - Python version: 3.8.0

**Additional context**
The query below seems work correctly. You can try it out and verify.
```SQL
SELECT datetime(visits.visit_time/1000000-11644473600, 'unixepoch', 'localtime') 
as 'visit_time', urls.url from visits INNER JOIN urls ON visits.url = urls.id 
WHERE visits.visit_duration > 0 ORDER BY visit_time DESC
```

**Comment by Samyak2** [comment]
@ObaraEmmanuel I can reproduce this on Chromium for Linux.
I can also confirm that your SQL query works without giving any spurious records.

I'll assign you to this issue if you're sending a PR for this.

Also, I wanted to say that I really appreciate you testing this package. Thank you!

**Comment by ObaraEmmanuel** [comment]
> A fix could be using the `Pathlib` library to construct a string same as the url. This way, the duplicates will map to the same string and can be eliminated if the time stamp is same.
> 
> Did I miss anything? 😅😅

@sujanchegu That's okay but would only be fixing it superficially. Modifying the SQL query can fix the problem at the source. Checkout the SQL query I suggested and tell me what you think.

**Comment by ObaraEmmanuel** [comment]
@Samyak2 First, I am also having a good time working with you guys; builds on my morale to contribute 😀. About the PR, I can get it done.

**Comment by Samyak2** [comment]
@ObaraEmmanuel can you direct the PR to `feature-bookmarks` branch since I've done some reformatting of the SQL queries there.

**Comment by ObaraEmmanuel** [comment]
Noted.
