### ISSUE TITLE
[FEATURE REQ] profile parameter in CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#74]
**Is your feature request related to a problem? Please describe.**
The CLI does not allow history to be exported from a specific profile (in case of browsers which support them) and the default is to get history from all profiles.

**Describe the solution you'd like**
A `-p`/`--profile` parameter that takes the name of the profile and calls the appropriate functions under `generic.Browser`.

This should show an error if the flag is used without a browser parameter (since profiles are specific to a browser) or if the browser does not support profiles.

Another flag `--show-profiles` (or `--list-profiles`) must be added that lists all available profiles for a given browser. This should also show errors on the same conditions as `--profile`.

**Additional context**
The [`profiles`](https://github.com/pesos/browser-history/blob/4bbdb6653691221f0c6ef9a672755ec839b23c4b/browser_history/generic.py#L89) and [`history_profiles`](https://github.com/pesos/browser-history/blob/4bbdb6653691221f0c6ef9a672755ec839b23c4b/browser_history/generic.py#L133) functions can be used for this (note: links might be outdated, find these functions on the master branch).

**Comment by ObaraEmmanuel** [comment]
I will look at this in the course of this week
