### ISSUE TITLE
[FEATURE REQ] Use logger instead of print in CLI

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#79]
**Is your feature request related to a problem? Please describe.**

When a (known) error occurs in the [CLI](https://github.com/pesos/browser-history/blob/master/browser_history/cli.py), the error message is printed as-is i.e., there is no indication that it is an error. This happens because the errors are printed using a simple `print` statement.

![image](https://user-images.githubusercontent.com/34161949/96165162-e38aa980-0f39-11eb-8bcd-da016d6e51af.png)

https://github.com/pesos/browser-history/blob/master/browser_history/cli.py#L74

Whereas info messages, shown when a browser is not installed/support, are indicated as such. This is because these are printed using a logger (which is from the `logging` module of python)

![image](https://user-images.githubusercontent.com/34161949/96165407-349a9d80-0f3a-11eb-9658-bb19ca4c3548.png)

https://github.com/pesos/browser-history/blob/4bbdb6653691221f0c6ef9a672755ec839b23c4b/browser_history/generic.py#L95

**Describe the solution you'd like**

Replace the error print statements with `logger.error` inside [cli.py](https://github.com/pesos/browser-history/blob/master/browser_history/cli.py). The logger can be found in [utils.py](https://github.com/pesos/browser-history/blob/master/browser_history/utils.py#L9)

**Describe alternatives you've considered**

An alternative would be to just append `ERROR: ` to the printed message, but that would be hacky workaround the real problem.

**Comment by RobertWetzler** [comment]
Hi, I'd like to work on this issue. Can you assign it to me?
