### ISSUE TITLE
[BROWSER] Support for edge on Linux

### ISSUE THREAD

**Issue by sujanchegu** [pesos/browser-history#80]
**Describe the browser and provide any links if available**
Browser name: Edge

**List the platforms supported by the browser to be added**
 Platforms: Linux

Additional Context: 

https://twitter.com/eMarcusNet/status/1308433470012747777?s=09

https://www.microsoftedgeinsider.com/en-us/

This issue will have to wait until the browser is released. :P

**Comment by sujanchegu** [comment]
Since Edge support is already present for MacOS and Windows, this should take much time. @Samyak2 tag it with good-first-issue?

**Comment by Samyak2** [comment]
Done

**Comment by Samyak2** [comment]
Since Microsoft Edge (Preview) is now on [Linux](https://www.microsoftedgeinsider.com/en-us/), this can be taken up. Edge is gaining popularity very quickly, we should add support soon.
