### ISSUE TITLE
[FEATURE REQ]  Code formatter/linter + pre-commit

### ISSUE THREAD

**Issue by gillesigot** [pesos/browser-history#84]
**Is your feature request related to a problem? Please describe.**
I usually use Black (https://github.com/psf/black) to format my code and flake8 (https://pypi.org/project/flake8/) to lint it (it covers more cases than pylint). Out of curiosity I ran both of them on current codebase and notice that it could be improved in several ways.

**Describe the solution you'd like**
If you are interested in such tools, I could apply them on code as it basically increase code readability and make it more compliant to PEP8.  
When done, I can also add a pre-commit hook to automate process when committing.

Feel free to comment should you have any thoughts on this :slightly_smiling_face:

**Comment by Samyak2** [comment]
That's a great idea!
I was thinking of some way to enforce code formatting. `pre-commit` sounds perfect for this.
You can go ahead and send a PR.

IIRC `flake8` requires some additional config to be compatible with `black` (for example, black allows 88 characters on line while flake8 limits it to 79).

Also, instructions for these will have to be added to `docs/contributing.rst`.

Also note that there was some formatting done using black on the `feature-bookmarks` branch. If you're planning to include reformatting in your PR, I would suggest you do it on that branch or wait for it to be merged (which will be done very soon).

**Comment by gillesigot** [comment]
Glad to hear that! :+1: 
So I think I'll first apply formatting (on `feature-bookmarks` branch) first, to avoid blocking anyone when pre-commit will be enable.

Then I'll add the pre-commit with proper config (indeed what comes up first to my mind is line length, I'll have a look if any other config customization is required) and doc update.
