### ISSUE TITLE
[TESTS/DOC] Tests fail trivially when run from `tests/`

### ISSUE THREAD

**Issue by sadielbartholomew** [pesos/browser-history#91]
The outcome of `test_browsers` depends on the directory it is run in, returning trivial failures due to the histories fetched being empty when `pytest` is run from the `browser-history/tests/` directory.

Based on what I saw in looking briefly into #90 it seems that in this project the `pytest` command was designed to be run from the `browser-history/` root directory instead, where the tests pass else error in a suitable way, but there is nothing in the documentation I can find to indicate this. It's not uncommon for tests to be designed to be run from the immediate directory containing them, so I feel there is the potential for confusion on the part of (potential) developers who may try to run from `tests/` and think there is an error giving empty histories, when really it is just the test suite run directory at issue.

Therefore I think it would be beneficial to others if some logic could be added to `test_browsers` to ensure there is no dependence on test run directory, or at least if the documentation could be explicit about the directories from which the tests can and cannot reliably be run, perhaps by stating the command(s) to use in the standard case. Thanks.

**Comment by Samyak2** [comment]
Thank you for opening this issue. A contributor had run into this issue previously. It would be ideal to make the tests independent of the directory they are run from.

The change would go near this line:

https://github.com/pesos/browser-history/blob/master/tests/utils.py#L13

**Comment by sadielbartholomew** [comment]
Thanks for the extra information, @Samyak2. I should be able to fix it by the end of tomorrow (UK time).
