### ISSUE TITLE
[FEATURE REQ]fetch history and bookmarks from default browser

### ISSUE THREAD

**Issue by ObaraEmmanuel** [pesos/browser-history#96]
**Is your feature request related to a problem? Please describe.**
Currently, it is possible to specify a specific browser or even all browsers but it would be interesting if you can specify that history and/or bookmarks be fetched from the default browser in use. This would most probably provide the most credible and recent history. I understand fetching from all browsers would work too but fetching from the default browser will provide the most recent and credible history all while having to only read from one browser.

**Describe the solution you'd like**
We could start by allowing `default` as a value to the `-b` argument. As for the implementation I am open to ideas.

**Comment by Samyak2** [comment]
Good idea!
The [webbrowser](https://docs.python.org/3/library/webbrowser.html) module can help with this (wow python has too many inbuilt modules xD).

```python
import webbrowser
c = webbrowser.get()
print(c.name) # or print(c.basename)
```

The above code gave `firefox` which is my default browser. It needs to be tested for other browsers too.

**Comment by ObaraEmmanuel** [comment]
In windows `c` is a `webbrowser.WindowsDefault` object and the `name` attribute is an empty string 😅!

**Comment by Samyak2** [comment]
For windows, I found these SOF questions:

[Question 1](https://stackoverflow.com/questions/32681951/how-to-get-name-of-the-default-browser-in-windows-using-python)

[Question 2](https://stackoverflow.com/questions/53926506/how-to-get-default-browser-name-using-python)

Though I haven't tested these.

**Comment by ObaraEmmanuel** [comment]
```python
>>> from winreg import HKEY_CURRENT_USER, OpenKey, QueryValueEx
>>> reg_path = r'Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice'
>>> with OpenKey(HKEY_CURRENT_USER, reg_path) as key:
...     print(QueryValueEx(key, 'ProgId'))
...
('ChromeHTML', 1)
```
The solution in [Question 2](https://stackoverflow.com/questions/53926506/how-to-get-default-browser-name-using-python) sorta works as you can see above. `ChromeHTML` is a weird name and would need us to preprocess. I was able to map out as many of the browsers on windows as I could:

|  Browser         | Registry value |
| --------------- | --------------- |
| Chrome          | ChromeHTML |
| Edge | MSEdgeHTM|
| Firefox | FirefoxURL-308046B0AF4A39CB|
| Opera | OperaStable |
| Internet Explorer | IE.HTTPS |
| Edge (Legacy) | AppX90nv6nhay5n6a98fnetv7tpk64pp35es |

As you can see, It's a jungle inside the registry. It is still possible to write a function that parses these names nonetheless.

**Comment by Samyak2** [comment]
Thank you for mapping out those values.

It indeed looks like a jungle haha, this feature will need quite a bit of manual work and some tricks.

Do you want to take up this issue? xD

**Comment by ObaraEmmanuel** [comment]
No problem, I will begin researching and working on it. We'll need a lot of collaborative effort to ensure it works on as many platforms as possible though.
