### ISSUE TITLE
[FEATURE REQ] Add codeclimate maintainibilty badge to README

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#97]
**Is your feature request related to a problem? Please describe.**

browser-history has been added to [codeclimate](https://codeclimate.com/github/pesos/browser-history). It would be nice to have the maintainability badge in the README along with the other badges.

**Describe the solution you'd like**

The maintainability badge from [here](https://codeclimate.com/github/pesos/browser-history/badges) should be added to the README.md (which is in markdown) after all the other badges.

**Describe alternatives you've considered**

None

**Additional context**

PR should be sent to the master branch.

**Comment by ayushontop** [comment]
I think issue is solved, close it .

**Comment by Samyak2** [comment]
Right, thank you for bringing this to my atttention.
